Repository UCF/campus-map-react, pull requests merged in 2024-07, with the labels that each got.

#36 Added informative meta tags and icons.
  index.html
  public/apple-touch-icon.jpg
  public/img/campus-map-OG.jpg
  public/ucf.ico
  public/vite.svg
Labels: enhancement

#37 Accessibility
  .env.template
  src/components/MapMenu.tsx
  src/main.tsx
Labels: enhancement

#38 added the google tag manager container in order to track the project.
  index.html
Labels: enhancement

#39 React ga4
  .env.template
  .github/workflows/azure-static-web-apps-delightful-moss-0832eaa0f.yml
  index.html
  package-lock.json
  package.json
  public/favicon.png
  public/vite.svg
  src/App.tsx
Labels: enhancement

#40 React ga4
  src/App.tsx
  src/components/MapMenu.tsx
  src/components/SearchResults.tsx
  src/services/LocationService.ts
Labels: enhancement

#41 added /map/ to the pathway of pageview.
  src/App.tsx
Labels: enhancement

#42 added the site-improve script
  index.html
Labels: enhancement

#44 Hf tracking
  .github/workflows/azure-static-web-apps-brave-wave-05c9ff40f.yml
  .github/workflows/azure-static-web-apps-lively-hill-0d219190f.yml
  src/App.tsx
Labels: bug

#46 Removed event tracking
  src/App.tsx
Labels: GA4
